apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cyberscore

resources:
  - namespace.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - celery-deployment.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: cyberscore
