global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "backend"
    metrics_path: /metrics
    static_configs:
      - targets: ["backend:8000"]
        labels:
          service: "mh-cyberscore-api"

  - job_name: "celery-worker"
    metrics_path: /metrics
    static_configs:
      - targets: ["celery-worker:9808"]
        labels:
          service: "mh-cyberscore-celery"
